version: 2.1

jobs:

  # ── JOB 1: Run Tests ──────────────────────────
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run unit tests
          command: pytest tests/ -v

  
   
  # ── JOB 2: Build & Push Docker Image ──────────
  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            IMAGE_NAME="$DOCKER_USERNAME/flask-devops-app"
            docker build -t "$IMAGE_NAME:latest" -t "$IMAGE_NAME:$CIRCLE_SHA1" .
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push to Docker Hub
          command: |
            IMAGE_NAME="$DOCKER_USERNAME/flask-devops-app"
            docker push "$IMAGE_NAME:latest"
            docker push "$IMAGE_NAME:$CIRCLE_SHA1"

  # ── JOB 3: Deploy to Render ───────────────────
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Trigger deployment on Render
          command: |
            curl -X POST $RENDER_DEPLOY_HOOK_URL

# ── WORKFLOW: defines job order ────────────────
workflows:
  ci-cd-pipeline:
    jobs:
      - test
      - build-and-push:
          requires:
            - test          # runs only if test passes ✅
      - deploy:
          requires:
            - build-and-push  # runs only if build passes ✅